---
title: "Risultati Simulazioni in locale"
author: "Francesco"
date: "`r Sys.Date()`"
format: gfm
---

## Note 

* Per ogni scenario ho simulato 4 repliche. Per ogni replica ho stimato il modello. 
* Nell'ultimo scenario ICL seleziona sempre tre stati

# Tempi
K2 Est 2: 42.64706 secs
K2 Est 3: 9.407718 hours
K2 Est 4: 8.611469 hours
K2 Est 2: 7.273578 mins
K2 Est 3: 5.454722 hours
K2 Est 4: 7.359757 hours
K 3 Est 3: 1.329551 mins
K 3 Est 3: 50.11197 mins
K 3 Est 4: 4.717821 hours
K 3 Est 2: 1.387711 mins
K 3 Est 3: 43.89449 mins
K 3 Est 4: 4.837073 hours
K 4 Est 2: 4.375683 mins
K 4 Est 3: 34.40716 mins
K 4 Est 4: 55.0696 mins
K 4 Est 2: 1.918118 mins
K 4 Est 3: 32.64197 mins
K 4 Est 4: 1.99168 hours

---

```{r setup, include=FALSE}
pacman::p_load(knitr, tidyverse, mclust)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

pacman::p_load(
    circular,
    tidyverse,
    sf,
    patchwork,
    knitr
)
source("code/fun_diagnostics.R")
formula <- ~ env + sex
```

```{r generate-report, results='asis'}
# Loop
for (scen in 1:6) {
    # Map real K to scen
    K <- dplyr::case_match(
        scen,
        1:2 ~ 2,
        3:4 ~ 3,
        5:6 ~ 4
    )

    # Print title
    cat(sprintf("## Scenario %d (True K = %d)\n\n", scen, K))

    # Model Selection table
    cat("### Model Selection\n\n")
    mod_sel <- mod.selection(K, scen) # Usa la versione aggiornata della funzione
    print(knitr::kable(mod_sel, format = "markdown", align = "c"))
    cat("\n\n")

    # Par estimation table
    cat("### Parameter Estimation\n\n")
    source("code/fun_estimation.R")
    load(paste0("data/simList_K", K, "n", scen, ".RData"))
    load(paste0("data/fit_K", K, "Kest", K, "n", scen, ".RData"))

    res <- purrr::map_dfr(1:4, function(i) {
        get.res.row(i = i, fitlist = fitlist, simlist = simlist, mod = mod, formula = formula)
    })

    tab_params <- res.summary(res, mod)

    print(knitr::kable(tab_params, format = "markdown", digits = 3, align = "c"))

    # Metrics
    cat(sprintf(
        "\n**Metriche Globali:** ARI Medio = %.3f | Converged Runs = %d / 4\n\n",
        attr(tab_params, "ARIMean"),
        attr(tab_params, "Converged")
    ))

    cat("---\n\n")
}
```
